spring.application.name=upyog-selenium-tests
server.port=8080
localhost=8080


# Selenium Grid Configuration (for Docker)
#false for local and true for server
selenium.grid.enabled=false
selenium.grid.url=http://selenium-chrome:4444/wd/hub
novnc.url=http://65.0.8.57:8000


# Selenium WebDriver Configuration
chrome.driver.path=/usr/local/bin/chromedriver
webdriver.wait.timeout=30
browser=chrome
timeout.explicit=30
citizen.base.url=https://niuatt.niua.in/upyog-ui/citizen/login
employee.base.url=https://niuatt.niua.in/upyog-ui/employee/login
employee.niuatt.base.url=https://niuatt.niua.in/upyog-ui/employee/login
city.name=Delhi
language.name=English
locality.name=Main Road Abadpura
mobile.number=7906413996

#EWASTE
module.ewaste.url=/upyog-ui/citizen/ew-home
ewaste.create.button=Create Ewaste Request
applicant.name=Arpit Rao
applicant.email=arpit@gmail.com

address.pincode=143001
address.street=Raj Nagar
address.doorNo=201
address.building=Jagbir Bhawan
address.line1=test address 1
address.line2=test address 2
address.landmark=test landmark
selected.city=Delhi

product.quantity=10

user.mobile=9999999999
user.otp=123456

#E-Waste Local
document.common.proof=Documents/Advertisement/advertisement.pdf
document.common.png=Documents/Asset-Management/send (1).png
#EWASTE
ewaste.login.username=EW_CEMP1
ewaste.login.password=eGov@123
ewaste.application.number=PG-EW-2026-05-25-001106
final.amount=1400
transaction.id=000321932743764

#ADV
adv.login.username=ADS_CEMP
adv.login.password=upyog@123
adv.application.number=ADV-1013-000217

#PT
module.propertTax.url=/upyog-ui/citizen/pt-home
property.type=Independent Building
property.login.username=PTSU
property.login.password=upyog@123
pt.application.number=PG-PT-1013-008738

#ASSET
asset.login.username=ASSET_INITIATOR
asset.login.password=eGov@123
asset1.login.username=ASSET_VERIFIER
asset1.login.password=eGov@123
asset2.login.username=ASSET_APPROVER
asset2.login.password=eGov@123
asset.application.number=PG-1013-2025-I-001329

#CHB
chb.login.username=CHB2
chb.login.password=upyog@123
chb.application.number=CHB-1508-000145

#CND
cnd.login.username=CND_SUPER
cnd.login.password=upyog@123
cnd.application.number=CND-1013-000021
cnd.mobile.number=9000453435

#OBPAS
architect.mobile.number=8888888881
document.drawing.dxf=Documents/OBPASDoc/OBPAS1.dxf
obpas.application.number=PG-SK-2026-03-16-005459
obpas.login.username=BPASU1
obpas.login.password=upyog@123
permit.number=
permit.date=



#PET
pet.login.username=PTRSU3
pet.login.password=upyog@123
pet.application.number=PG-PTR-2026-02-24-000139

#PGR
pgr.login.username=PGRSU
pgr.login.password=upyog@123
pgr.application.number=PG-PGR-2026-05-20-002518

#MOBILE_TOILET
mt.login.username=MTCEMP
mt.login.password=eGov@123
mt.application.number=MT-1013-001194
toilet.vendor.mobile.number=9800000000

#TREE_PRUNING
tp.login.username=TPCEMP
tp.login.password=eGov@123
tp.application.number=TP-1013-000173

#WATER_TANKER
wt.login.username=WTCEMP
wt.login.password=eGov@123
wt.application.number=WT-1013-001197
water.vendor.mobile.number=7033145533



#SV
sv.login.username=SV_CEMP
sv.login.password=upyog@123
sv.application.number=SV-1013-000113


#TL
tl.login.username=TLSU1
tl.login.password=upyog@123
tl.application.number=PG-TL-2026-05-20-005526

#WATER
ws.login.username=WSSU2
ws.login.password=upyog@123
ws.application.number=WS_AP/1013/2026-27/001416
sw.application.number=SW_AP/1013/2026-27/000700


#DESLUDGING
fsm.login.username=QAEE
fsm.login.password=upyog@123
fsm.application.number=FSM-1013-2026-05-12-001423
fstpo.login.username=QAFSTPO
fstpo.login.password=upyog@123




