citizen.base.url=https://upyog.niua.org/upyog-ui/citizen/login
employee.base.url=https://upyog.niua.org/upyog-ui/employee/login
city.name=Delhi
language.name=English
locality.name=Main Road Abadpura
mobile.number=9999999999

#EWASTE
module.ewaste.url=/upyog-ui/citizen/ew-home
ewaste.create.button=Create Ewaste Request
applicant.name=Arpit Rao
applicant.email=arpit@gmail.com

address.pincode=143001
address.street=Raj Nagar
address.doorNo=201
address.building=Jagbir Bhawan
address.line1=test address 1
address.line2=test address 2
address.landmark=test landmark

product.quantity=10

user.mobile=9999999999
user.otp=123456

#E-Waste Local
document.EwasteImage.proof=/Users/niua-l1232/Documents/automation_upyog/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Advertisement/acknowledgement (24).pdf

#EWASTE
ewaste.login.username=EWASTE
ewaste.login.password=upyog@123
ewaste.application.number=PG-EW-2026-04-29-000092
final.amount=1400
transaction.id=000321932743764

