server.workDir-path=/upyog-data-dx

server.port=8281
server.context-path=/upyog-data-dx
server.servlet.context-path=/upyog-data-dx
logging.level.org.egov=DEBUG


#DATABASE CONFIGURATION
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/upyog-pfms
spring.datasource.username=postgres
spring.datasource.password=postgres

#FLYWAY CONFIGURATION
spring.flyway.url=jdbc:postgresql://localhost:5432/upyog-pfms
spring.flyway.user=postgres
spring.flyway.password=postgres
#spring.flyway.table=public
spring.flyway.baseline-on-migrate=true
spring.flyway.outOfOrder=true
spring.flyway.locations=classpath:/db/migration/main
spring.flyway.enabled=true


# KAFKA SERVER CONFIGURATIONS
kafka.config.bootstrap_server_config=localhost:9092
spring.kafka.consumer.value-deserializer=org.egov.tracer.kafka.deserializer.HashMapDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=citizen-request-service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.properties.spring.json.use.type.headers=false


# KAFKA CONSUMER CONFIGURATIONS
kafka.consumer.config.auto_commit=true
kafka.consumer.config.auto_commit_interval=100
kafka.consumer.config.session_timeout=15000
kafka.consumer.config.auto_offset_reset=earliest

# KAFKA PRODUCER CONFIGURATIONS
kafka.producer.config.retries_config=0
kafka.producer.config.batch_size_config=16384
kafka.producer.config.linger_ms_config=1
kafka.producer.config.buffer_memory_config=33554432



# PERSISTER CONFIG
upyog.data.kafka.topic=state-to-upyog-data-exchange

# PFMS API Configuration
pfms.auth.url=https://training.pfms.gov.in/UMGAPI/API/Auth/ValidLogin
pfms.data.url=https://training.pfms.gov.in/UMGAPI/API/ULBAPI/GetTransactionalDataFetchedFromULBSystem
pfms.auth.username=UMANG_API
pfms.auth.password=Passwaord
pfms.client.ip=15.206.142.28

# Scheduler - daily 2AM
pfms.scheduler.cron=0 0 2 * * *
pfms.scheduler.batch.size=50
# Retry Scheduler - daily at % AM by default
pfms.retry.scheduler.cron=0 0 5 * * *
