spring.application.name=upyog-selenium-tests
server.port=9589
# Selenium WebDriver Configuration
chrome.driver.path=/usr/local/bin/chromedriver
webdriver.wait.timeout=30

# Chrome Browser Options
chrome.option.1=--remote-allow-origins=*
chrome.option.2=--disable-blink-features=AutomationControlled
chrome.option.3=--start-maximized
chrome.option.4=--disable-autofill
chrome.option.5=--disable-autofill-keyboard-accessory-view
chrome.option.6=--disable-full-form-autofill-ios
chrome.option.7=--disable-save-password-bubble

# Chrome Preferences
chrome.prefs.autofill.address_enabled=false
chrome.prefs.autofill.profile_enabled=false

# Test Data Configuration
test.otp=123456
test.city.name=City A Muncipal Corporation

# Application URLs
employee.base.url=https://upyog-test.niua.org/upyog-ui/employee/user/login
citizen.base.url=https://upyog-test.niua.org/upyog-ui/citizen/login

#Application sv url
sv.employee.base.url=https://upyog-test.niua.org/sv-ui/employee/user/login

# Login Credentials
app.login.username=PTRCEMP
app.login.password=eGov@123

tl.login.username=TLCE1
tl.login.password=eGov@123
citizen.mobile.number=9999999999
architect.mobile.number=7272727216


//SVLOGIN
sv.login.username=SV_CEMP
SV.login.password=upyogTest@123





# Employee Configuration
tl.application.number=PG-TL-2025-08-18-005174
pet.application.number=PG-PTR-2025-08-18-000117
sv.application.number=SV-1013-000049
ast.application.number=PG-1013-2025-I-001334

# Document Upload Paths
document.identity.proof=/Users/kaveri/Downloads/doc.pdf
document.owner.proof=/Users/kaveri/Downloads/owner.pdf
document.vaccination.cert=/Users/kaveri/Downloads/vaccination.pdf
document.fitness.cert=/Users/kaveri/Downloads/fitness.pdf
document.pet.photo=/Users/kaveri/Downloads/deep.png

#Advertisement
document.sampleDocument.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Advertisement/acknowledgement (24).pdf
document.address.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Advertisement/acknowledgement (24).pdf
document.Identity.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Advertisement/acknowledgement (24).pdf

#TreePruning
document.site.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/TreePrunining/acknowledgement (25).pdf

#Property Tax
document.propertyaddress.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/PropertyTax/acknowledgement (21).pdf
document.propertyidentity.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/PropertyTax/acknowledgement (21).pdf

#Public Grievance Redressal
document.complaint.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/pgr/wave.png

#OBPAS
document.drawing.dxf=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/OBPAS1.dxf
document.iDentity.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.aDdress.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.landTax.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.titleDeedOfTheProperty.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.layoutApprovalCopy.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.structuralStabilityCertificate.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.locationSketchAndVillageSketch.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.sitePlan.proof=/Users/niua-l1232/Downloads/acknowledgement (26).pdf
document.floorPlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf
document.servicePlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf
document.elevationPlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf
document.sectionPlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf
document.parkingPlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf
document.roofPlan.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/acknowledgement (5).pdf

#E-Waste
document.EwasteImage.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/E-WASTE/WATER COOLER.png

#Asset-Management
document.asset.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Asset-Management/acknowledgement (26).pdf
document.asset1.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/Asset-Management/send (1).png
document.asset2.proof=/Users/niua-l1232/Desktop/upyog-new/arpit-estate/new/UPYOG-NIUA-Arpit/upyog-automation-test ing/src/main/resources/Documents/Asset-Management/acknowledgement (26).pdf